pipeline {

    agent any

    environment {

        AWS_REGION = "ap-south-1"
        APP_NAME = "cloud-native-cicd-app"

        ALB_LISTENER_ARN = "arn:aws:elasticloadbalancing:ap-south-1:606639293354:listener/app/cloud-native-cicd-alb/63978839430bf6dd/f1c1d32cc81ec141"

        BLUE_TARGET_GROUP_ARN = "arn:aws:elasticloadbalancing:ap-south-1:606639293354:targetgroup/cloud-native-cicd-blue/847d5087d082ab09"

        GREEN_TARGET_GROUP_ARN = "arn:aws:elasticloadbalancing:ap-south-1:606639293354:targetgroup/cloud-native-cicd-green/61c4e3fa24f7deb3"
    }

    stages {

        stage('Checkout') {

            steps {

                checkout scm
            }
        }

        stage('Prepare Scripts') {

            steps {

                sh 'chmod +x jenkins/scripts/*.sh'
            }
        }

        stage('Build Test Push') {

            steps {

                sh './jenkins/scripts/build.sh'
            }
        }

        stage('Deploy Green') {

            steps {

                sh './jenkins/scripts/deploy.sh green'
            }
        }

        stage('Validate Green') {

            steps {

                sh './jenkins/scripts/validate.sh green'
            }
        }

        stage('Manual Approval') {

            steps {

                timeout(time: 10, unit: 'MINUTES') {

                    input 'Switch traffic to GREEN?'
                }
            }
        }

        stage('Switch Traffic') {

            steps {

                sh './jenkins/scripts/traffic.sh green'
            }
        }
    }

    post {

        success {

            sh './jenkins/scripts/notify.sh SUCCESS'
        }

        failure {

            sh './jenkins/scripts/deploy.sh blue'

            sh './jenkins/scripts/traffic.sh blue'

            sh './jenkins/scripts/notify.sh FAILURE'
        }
    }
}