pipeline {

    agent any

    environment {

        AWS_REGION = "ap-south-1"
        APP_NAME = "cloud-native-cicd-app"

    }

    stages {

        stage('Checkout') {

            steps {

                checkout scm
            }
        }

        stage('Load Terraform Outputs') {

            steps {

                script {

                    env.ALB_LISTENER_ARN = sh(
                        script: '''
                        terraform -chdir=infrastructure/terraform output -raw alb_listener_arn
                        ''',
                        returnStdout: true
                    ).trim()

                    env.BLUE_TARGET_GROUP_ARN = sh(
                        script: '''
                        terraform -chdir=infrastructure/terraform output -raw blue_target_group_arn
                        ''',
                        returnStdout: true
                    ).trim()

                    env.GREEN_TARGET_GROUP_ARN = sh(
                        script: '''
                        terraform -chdir=infrastructure/terraform output -raw green_target_group_arn
                        ''',
                        returnStdout: true
                    ).trim()

                    echo "Terraform outputs loaded"
                    echo "ALB Listener ARN: ${env.ALB_LISTENER_ARN}"
                }
            }
        }

        stage('Build Test Push') {

            steps {

                sh '''
                    chmod +x jenkins/scripts/*.sh
                    ./jenkins/scripts/build.sh
                '''
            }
        }

        stage('Deploy Green') {

            steps {

                sh './jenkins/scripts/deploy.sh green'
            }
        }

        stage('Validate Green') {

            steps {

                sh './jenkins/scripts/validate.sh green'
            }
        }

        stage('Manual Approval') {

            steps {

                timeout(time: 10, unit: 'MINUTES') {

                    input 'Switch traffic to GREEN?'
                }
            }
        }

        stage('Switch Traffic') {

            steps {

                sh '''
                    export ALB_LISTENER_ARN=${ALB_LISTENER_ARN}
                    export BLUE_TARGET_GROUP_ARN=${BLUE_TARGET_GROUP_ARN}
                    export GREEN_TARGET_GROUP_ARN=${GREEN_TARGET_GROUP_ARN}

                    ./jenkins/scripts/traffic.sh green
                '''
            }
        }
    }

    post {

        success {

            sh './jenkins/scripts/notify.sh SUCCESS'
        }

        failure {

            sh './jenkins/scripts/deploy.sh blue'

            sh '''
                export ALB_LISTENER_ARN=${ALB_LISTENER_ARN}
                export BLUE_TARGET_GROUP_ARN=${BLUE_TARGET_GROUP_ARN}
                export GREEN_TARGET_GROUP_ARN=${GREEN_TARGET_GROUP_ARN}

                ./jenkins/scripts/traffic.sh blue
            '''

            sh './jenkins/scripts/notify.sh FAILURE'
        }
    }
}